dist: trusty

language: java

jdk:
  - oraclejdk7

# install thrift
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install thrift-compiler

install: gradle -q assemble

script: gradle clean check distZip --stacktrace