dist: trusty

language: java

jdk:
  - oraclejdk7

# install thrift
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
  - wget http://www.us.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz
  - tar xfz thrift-0.9.3.tar.gz
  - cd thrift-0.9.3 && ./configure --without-ruby --without-nodejs && sudo make install

install: gradle -q assemble

script: gradle clean check distZip --stacktrace